title   Djiancoeg
linux   /vmlinuz-linux-lts
initrd  /amd-ucode.img
initrd  /initramfs-linux-lts.img

options root=/dev/nvme0n1p3 rw rootflags=subvol=@ 8250.nr_uarts=0
#options root=UUID=36b90b59-88c4-4a74-9c1f-4449607db5b4 rw rootflags=subvol=@ 8250.nr_uarts=0
